// <auto-generated/>
#pragma warning disable
#nullable enable

using System.Runtime.CompilerServices;

using Cysharp.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

using TedToolkit.RoslynHelper.Generators.Delegates;

namespace TedToolkit.RoslynHelper.Generators;

public record struct SourceFile(string FileName):
    IMemberOwner
{
    /// <summary>
    /// Generate the code
    /// </summary>
    /// <param name="context">context</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Generate(SourceProductionContext context)
    {
        context.AddSource(FileName + ".g.cs", ToCode());
    }

    public string ToCode()
    {
        var builder = new SourceBuilder();
        try
        {
            builder.Append("""
                           //------------------------------------------------------------------------------
                           // <auto-generated>
                           //    This code was generated from a template.
                           //
                           //    Manual changes to this file may cause unexpected behavior in your application.
                           //    Manual changes to this file will be overwritten if the code is regenerated.
                           // </auto-generated>
                           //------------------------------------------------------------------------------
                           """);
            builder.AppendLine();

            builder.Append("#pragma warning disable");
            builder.AppendLine();

            this.AddMembers(ref builder);
            return builder.ToCode();
        }
        finally
        {
            builder.Dispose();
        }
    }

    public List<MemberHandler> Members
        => field ??= [];
}