// -----------------------------------------------------------------------
// <copyright file="SourceFile.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Runtime.CompilerServices;

using Cysharp.Text;

using Microsoft.CodeAnalysis;

using TedToolkit.RoslynHelper.Generators.Delegates;
using TedToolkit.RoslynHelper.Generators.Types;

namespace TedToolkit.RoslynHelper.Generators;

/// <summary>
/// The source file
/// </summary>
/// <param name="FileName">file name</param>
public record struct SourceFile(string FileName)
{
    /// <summary>
    /// Generate the code
    /// </summary>
    /// <param name="context">context</param>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Generate(scoped in SourceProductionContext context)
        => context.AddSource(ZString.Concat(FileName, ".g.cs"), ToCode());

    /// <summary>
    /// To code
    /// </summary>
    /// <returns>the code</returns>
    public string ToCode()
    {
        var builder = new SourceBuilder();
        try
        {
            builder.Append("""
                           //------------------------------------------------------------------------------
                           // <auto-generated>
                           //    This code was generated from a template.
                           //
                           //    Manual changes to this file may cause unexpected behavior in your application.
                           //    Manual changes to this file will be overwritten if the code is regenerated.
                           // </auto-generated>
                           //------------------------------------------------------------------------------
                           """);
            builder.AppendLine();
            builder.AppendLine();

            builder.Append("#pragma warning disable");
            builder.AppendLine();

            foreach (var member in NameSpaces)
            {
                builder.AppendLine();
                member.ToCode(ref builder);
            }

            return builder.ToCode();
        }
#pragma warning disable CA1031
        catch (Exception? e)
#pragma warning restore CA1031
        {
            using var exceptionBuilder = ZString.CreateStringBuilder();
            while (e is not null)
            {
                exceptionBuilder.AppendLine(e.Message);
                exceptionBuilder.AppendLine(e.StackTrace);
                exceptionBuilder.Append('-', 50);
                exceptionBuilder.AppendLine();
                e = e.InnerException;
            }

            return exceptionBuilder.ToString();
        }
        finally
        {
            builder.Dispose();
        }
    }

    /// <summary>
    /// NameSpaces
    /// </summary>
#pragma warning disable S2325
    public List<NameSpace> NameSpaces
#pragma warning restore S2325
        => field ??= [];
}