// -----------------------------------------------------------------------
// <copyright file="GeneratedRewriter.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

using static TedToolkit.RoslynHelper.Extensions.SyntaxExtensions;

namespace TedToolkit.RoslynHelper;

/// <summary>
///     Add the autogenerated information to the node.
/// </summary>
/// <param name="type">The type.</param>
public class GeneratedRewriter(Type type) : CSharpSyntaxRewriter
{
    /// <inheritdoc />
    public override SyntaxNode? VisitCompilationUnit(CompilationUnitSyntax node)
    {
        if (node is null)
            throw new ArgumentNullException(nameof(node));

        var newLeadingTrivia = node.GetLeadingTrivia()
            .Insert(0, Comment("// <auto-generated/>"))
            .Add(Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true)))
            .Add(Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true)));
        var newNode = node.WithLeadingTrivia(newLeadingTrivia);
        return base.VisitCompilationUnit(newNode);
    }

    /// <inheritdoc />
    public override SyntaxNode? VisitMethodDeclaration(MethodDeclarationSyntax node)
    {
        if (node is null)
            throw new ArgumentNullException(nameof(node));

        var leadingTrivia = node.GetLeadingTrivia();
        var newNode = node
            .WithoutLeadingTrivia()
            .WithAttributeLists(node.AttributeLists.Add(GeneratedCodeAttribute(type)
                .AddAttributes(NonUserCodeAttribute())))
            .WithLeadingTrivia(leadingTrivia);
        return base.VisitMethodDeclaration(newNode);
    }

    /// <inheritdoc />
    public override SyntaxNode? VisitPropertyDeclaration(PropertyDeclarationSyntax node)
    {
        if (node is null)
            throw new ArgumentNullException(nameof(node));

        var leadingTrivia = node.GetLeadingTrivia();
        var newNode = node
            .WithoutLeadingTrivia()
            .WithAttributeLists(node.AttributeLists.Add(GeneratedCodeAttribute(type)
                .AddAttributes(NonUserCodeAttribute())))
            .WithLeadingTrivia(leadingTrivia);
        return base.VisitPropertyDeclaration(newNode);
    }

    /// <inheritdoc />
    public override SyntaxNode? VisitFieldDeclaration(FieldDeclarationSyntax node)
    {
        if (node is null)
            throw new ArgumentNullException(nameof(node));

        var leadingTrivia = node.GetLeadingTrivia();
        var newNode = node
            .WithoutLeadingTrivia()
            .WithAttributeLists(node.AttributeLists.Add(GeneratedCodeAttribute(type)))
            .WithLeadingTrivia(leadingTrivia);
        return base.VisitFieldDeclaration(newNode);
    }

    /// <inheritdoc />
    public override SyntaxNode? VisitStructDeclaration(StructDeclarationSyntax node)
    {
        if (node is null)
            throw new ArgumentNullException(nameof(node));

        var leadingTrivia = node.GetLeadingTrivia();
        var newNode = node
            .WithoutLeadingTrivia()
            .WithAttributeLists(node.AttributeLists.Add(GeneratedCodeAttribute(type)
                .AddAttributes(NonUserCodeAttribute())))
            .WithLeadingTrivia(leadingTrivia);
        return base.VisitStructDeclaration(newNode);
    }

    /// <inheritdoc />
    public override SyntaxNode? VisitClassDeclaration(ClassDeclarationSyntax node)
    {
        if (node is null)
            throw new ArgumentNullException(nameof(node));

        var leadingTrivia = node.GetLeadingTrivia();
        var newNode = node
            .WithoutLeadingTrivia()
            .WithAttributeLists(node.AttributeLists.Add(GeneratedCodeAttribute(type)
                .AddAttributes(NonUserCodeAttribute())))
            .WithLeadingTrivia(leadingTrivia);
        return base.VisitClassDeclaration(newNode);
    }

    /// <inheritdoc />
    public override SyntaxNode? VisitConstructorDeclaration(ConstructorDeclarationSyntax node)
    {
        if (node is null)
            throw new ArgumentNullException(nameof(node));

        var leadingTrivia = node.GetLeadingTrivia();
        var newNode = node
            .WithoutLeadingTrivia()
            .WithAttributeLists(node.AttributeLists.Add(GeneratedCodeAttribute(type)
                .AddAttributes(NonUserCodeAttribute())))
            .WithLeadingTrivia(leadingTrivia);
        return base.VisitConstructorDeclaration(newNode);
    }

    /// <inheritdoc />
    public override SyntaxNode? VisitDestructorDeclaration(DestructorDeclarationSyntax node)
    {
        if (node is null)
            throw new ArgumentNullException(nameof(node));

        var leadingTrivia = node.GetLeadingTrivia();
        var newNode = node
            .WithoutLeadingTrivia()
            .WithAttributeLists(node.AttributeLists.Add(GeneratedCodeAttribute(type)
                .AddAttributes(NonUserCodeAttribute())))
            .WithLeadingTrivia(leadingTrivia);
        return base.VisitDestructorDeclaration(newNode);
    }
}