// -----------------------------------------------------------------------
// <copyright file="SourceFile.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

using System.Runtime.CompilerServices;

using Cysharp.Text;

using Microsoft.CodeAnalysis;

using TedToolkit.RoslynHelper.Syntaxes;

namespace TedToolkit.RoslynHelper;

/// <summary>
/// The source file.
/// </summary>
public class SourceFile()
{
    /// <summary>
    /// Generate the code.
    /// </summary>
    /// <param name="context">context.</param>
    /// <param name="fileName">file name.</param>
    /// <exception cref="ArgumentNullException">fileName is null.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public void Generate(scoped in SourceProductionContext context, string fileName)
    {
        if (context.CancellationToken.IsCancellationRequested)
        {
            return;
        }

        var code = ToCode();

        if (context.CancellationToken.IsCancellationRequested)
        {
            return;
        }

        if (fileName is null)
        {
            throw new ArgumentNullException(nameof(fileName));
        }

        context.AddSource(ZString.Concat(fileName.ToHintNameKeepDot(), ".g.cs"), code);
    }

    /// <summary>
    /// To code.
    /// </summary>
    /// <returns>the code.</returns>
    public string ToCode()
    {
        var builder = new SourceBuilder();
        try
        {
            builder.Append("""
                           //------------------------------------------------------------------------------
                           // <auto-generated>
                           //    This code was generated from a template.
                           //
                           //    Manual changes to this file may cause unexpected behavior in your application.
                           //    Manual changes to this file will be overwritten if the code is regenerated.
                           // </auto-generated>
                           //------------------------------------------------------------------------------
                           """);
            builder.AppendLine();
            builder.AppendLine();

            builder.Append("#pragma warning disable");
            builder.AppendLine();

            foreach (var attribute in Attributes)
            {
                builder.AppendLine();

                if (attribute.Condition is not null)
                {
                    builder.Append("#if ");
                    attribute.Condition.ToCode(ref builder);
                    builder.AppendLine();
                }

                builder.Append('[');
                attribute.Item.ToCode(ref builder);
                builder.Append(']');

                if (attribute.Condition is not null)
                {
                    builder.AppendLine();
                    builder.Append("#endif");
                }
            }

            foreach (var usingDirective in Usings)
            {
                builder.AppendLine();
                usingDirective.ToCode(ref builder);
            }

            foreach (var nameSpace in NameSpaces)
            {
                builder.AppendLine();
                nameSpace.ToCode(ref builder);
            }

            return builder.ToCode();
        }
#pragma warning disable CA1031
        catch (Exception? e)
#pragma warning restore CA1031
        {
            using var exceptionBuilder = ZString.CreateStringBuilder();
            while (e is not null)
            {
                exceptionBuilder.AppendLine(e.Message);
                exceptionBuilder.AppendLine(e.StackTrace);
                exceptionBuilder.Append('-', 50);
                exceptionBuilder.AppendLine();
                e = e.InnerException;
            }

            return exceptionBuilder.ToString();
        }
        finally
        {
            builder.Dispose();
        }
    }

    /// <summary>
    /// Gets nameSpaces.
    /// </summary>
#pragma warning disable S2325
    public List<NameSpace> NameSpaces
#pragma warning restore S2325
        => field ??= [];

    /// <summary>
    /// Gets attributes.
    /// </summary>
#pragma warning disable S2325
    public List<ConditionalItem<Syntaxes.Attribute>> Attributes
#pragma warning restore S2325
        => field ??= [];

    /// <summary>
    /// Gets file-level using directives.
    /// </summary>
#pragma warning disable S2325
    public List<UsingDirective> Usings
#pragma warning restore S2325
        => field ??= [];

    /// <summary>
    /// Add a name space.
    /// </summary>
    /// <param name="nameSpace">the namespace.</param>
    /// <returns>result.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public SourceFile AddNameSpace(NameSpace nameSpace)
    {
        NameSpaces.Add(nameSpace);
        return this;
    }

    /// <summary>
    /// Add a file-level using directive.
    /// </summary>
    /// <param name="usingDirective">the using directive.</param>
    /// <returns>result.</returns>
    /// <exception cref="ArgumentNullException">usingDirective is null.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public SourceFile AddUsing(UsingDirective usingDirective)
    {
        if (usingDirective is null)
        {
            throw new ArgumentNullException(nameof(usingDirective));
        }

        Usings.Add(usingDirective);
        return this;
    }

    /// <summary>
    /// Add a name space.
    /// </summary>
    /// <param name="attribute">the attribute.</param>
    /// <param name="condition">the optional conditional compilation expression.</param>
    /// <returns>result.</returns>
    /// <exception cref="ArgumentNullException">attribute is null.</exception>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public SourceFile AddAttribute(Syntaxes.Attribute attribute, Syntaxes.Preprocessors.PreprocessorExpression? condition = null)
    {
        if (attribute is null)
        {
            throw new ArgumentNullException(nameof(attribute));
        }

        attribute.Modifier = AttributeModifier.ASSEMBLY;
        Attributes.Add(new ConditionalItem<Syntaxes.Attribute>(attribute, condition));
        return this;
    }
}