using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using TedToolkit.RoslynHelper.Syntaxes;

namespace TedToolkit.RoslynHelper.Tests;

internal sealed class SourceFileOptionsTests
{
    /// <summary>
    /// Defaults preserve the existing header, warning suppression, and absent nullable directive.
    /// </summary>
    [Test]
    public async Task Should_preserve_default_file_options()
    {
        var file = new SourceFile();
        var code = file.ToCode();
        await Assert.That(file.DisableWarnings).IsTrue();
        await Assert.That(file.NullableContext).IsNull();
        await Assert.That(code).Contains("// <auto-generated>");
        await Assert.That(code).Contains("#pragma warning disable");
        await Assert.That(code.Contains("#nullable", StringComparison.Ordinal)).IsFalse();
        await Assert.That(new SourceFile().AddNameSpace(new NameSpace("Empty")).ToCode()).Contains("namespace Empty;");
    }

    /// <summary>
    /// File-level usings, assembly attributes, global types, and multiple namespaces compile together.
    /// </summary>
    [Test]
    public async Task Should_compile_root_members_with_usings_attributes_and_namespaces()
    {
        var file = new SourceFile { DisableWarnings = false, NullableContext = NullableContextOptions.Enable }
            .AddUsing(SourceComposer.Using("System"))
            .AddAttribute(SourceComposer.Attribute<System.Reflection.AssemblyTitleAttribute>().AddArgument("Generated".ToLiteral()))
            .AddMember(new TypeDeclaration("GlobalWorker", TypeDeclarationType.CLASS).Public
                .AddMember(new Field(new DataType("DateTime"), "Timestamp").Public))
            .AddNameSpace(new NameSpace("Empty"))
            .AddNameSpace(new NameSpace("Named").AddMember(new TypeDeclaration("Worker", TypeDeclarationType.CLASS).Public
                .AddMember(new Method("Run").Public)));
        var code = file.ToCode();
        var compilation = RoslynTestHelper.CreateCompilation(code);

        await Assert.That(RoslynTestHelper.GetNamedType(compilation, "GlobalWorker").ContainingNamespace.IsGlobalNamespace).IsTrue();
        await Assert.That(RoslynTestHelper.GetNamedType(compilation, "Named.Worker").Name).IsEqualTo("Worker");
        await Assert.That(code.IndexOf("using System;", StringComparison.Ordinal))
            .IsLessThan(code.IndexOf("[assembly:", StringComparison.Ordinal));
        await Assert.That(code.Contains("namespace Empty;", StringComparison.Ordinal)).IsFalse();
    }

    /// <summary>
    /// Empty namespaces become blocks when they share a file, even without root types.
    /// </summary>
    [Test]
    public async Task Should_compile_multiple_empty_namespaces()
    {
        var code = new SourceFile().AddNameSpace(new NameSpace("First")).AddNameSpace(new NameSpace("Second")).ToCode();
        var compilation = RoslynTestHelper.CreateCompilation(code);
        await Assert.That(compilation.SyntaxTrees.Single().GetRoot().DescendantNodes().OfType<NamespaceDeclarationSyntax>().Count())
            .IsEqualTo(2);
    }

    /// <summary>
    /// Each nullable mode sets both annotation and warning states regardless of compilation defaults.
    /// </summary>
    [Test]
    [Arguments(NullableContextOptions.Disable, false, false)]
    [Arguments(NullableContextOptions.Enable, true, true)]
    [Arguments(NullableContextOptions.Annotations, true, false)]
    [Arguments(NullableContextOptions.Warnings, false, true)]
    public async Task Should_emit_requested_nullable_context(NullableContextOptions context, bool annotations, bool warnings)
    {
        var method = new Method("Length", new ReturnType(DataType.Int)).Public
            .AddParameter(new Parameter(DataType.String, "text"))
            .AddStatement("text".ToSimpleName().Sub("Length").Return);
        var code = new SourceFile { NullableContext = context, DisableWarnings = false }
            .AddMember(new TypeDeclaration("Worker", TypeDeclarationType.CLASS).AddMember(method)).ToCode();
        var compilation = RoslynTestHelper.CreateCompilation(code);
        var syntax = compilation.SyntaxTrees.Single();
        var position = syntax.GetRoot().DescendantNodes().OfType<ReturnStatementSyntax>().Single().SpanStart;
        var actual = compilation.GetSemanticModel(syntax).GetNullableContext(position);

        await Assert.That((actual & NullableContext.AnnotationsEnabled) != 0).IsEqualTo(annotations);
        await Assert.That((actual & NullableContext.WarningsEnabled) != 0).IsEqualTo(warnings);
    }

    /// <summary>
    /// Generated-code warnings, including nullable dereferences, are visible when suppression is disabled.
    /// </summary>
    [Test]
    [Arguments(false)]
    [Arguments(true)]
    public async Task Should_control_warning_suppression(bool disableWarnings)
    {
        var method = new Method("Length", new ReturnType(DataType.Int)).Public
            .AddParameter(new Parameter(DataType.String.Null, "text"))
            .AddStatement(new VariableExpression(DataType.Int, "unused").AddDefault(1.ToLiteral()))
            .AddStatement("text".ToSimpleName().Sub("Length").Return);
        var code = new SourceFile { DisableWarnings = disableWarnings, NullableContext = NullableContextOptions.Enable }
            .AddMember(new TypeDeclaration("Worker", TypeDeclarationType.CLASS).AddMember(method)).ToCode();
        var diagnostics = RoslynTestHelper.CreateCompilation(code).GetDiagnostics();

        await Assert.That(diagnostics.Any(diagnostic => diagnostic.Id == "CS8602")).IsEqualTo(!disableWarnings);
        await Assert.That(diagnostics.Any(diagnostic => diagnostic.Id == "CS0219")).IsEqualTo(!disableWarnings);
    }
}