// -----------------------------------------------------------------------
// <copyright file="SyntaxExtensions.cs" company="TedToolkit">
// Copyright (c) TedToolkit. All rights reserved.
// Licensed under the LGPL-3.0 license. See COPYING, COPYING.LESSER file in the project root for full license information.
// </copyright>
// -----------------------------------------------------------------------

#pragma warning disable
using System.Runtime.CompilerServices;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

using TedToolkit.RoslynHelper.Names;

using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace TedToolkit.RoslynHelper.Extensions;

/// <summary>
///     The extensions for the <see cref="Microsoft.CodeAnalysis.CSharp.SyntaxFactory" />.
/// </summary>
[Obsolete("Do not use this method, try to use the generators instead!")]
public static class SyntaxExtensions
{
    /// <summary>
    ///     Add the comment.
    /// </summary>
    /// <typeparam name="TNode">the syntax node type.</typeparam>
    /// <param name="node">the syntax node.</param>
    /// <param name="comment">the XML comment text.</param>
    /// <returns>the node with leading comment trivia.</returns>
    public static TNode WithXmlComment<TNode>(this TNode node, string comment = "/// <summary/>")
        where TNode : SyntaxNode
    {
        return node.WithLeadingTrivia(TriviaList([Comment(comment)]));
    }

    /// <summary>
    ///     Add the comment with inheritdoc.
    /// </summary>
    /// <param name="node">the syntax node.</param>
    /// <param name="name">the name to reference in the cref attribute.</param>
    /// <typeparam name="TNode">the syntax node type.</typeparam>
    /// <returns>the node with inheritdoc comment trivia.</returns>
    public static TNode WithXmlCommentInheritDoc<TNode>(this TNode node, IName? name = null)
        where TNode : SyntaxNode
    {
        return node.WithXmlCommentInheritDoc(name?.SummaryName);
    }

    /// <summary>
    ///     Add the comment with inheritdoc.
    /// </summary>
    /// <param name="node">the syntax node.</param>
    /// <param name="name">the cref string to reference.</param>
    /// <typeparam name="TNode">the syntax node type.</typeparam>
    /// <returns>the node with inheritdoc comment trivia.</returns>
    public static TNode WithXmlCommentInheritDoc<TNode>(this TNode node, string? name = null)
        where TNode : SyntaxNode
    {
        return node.WithXmlComment(name is null
            ? "/// <inheritdoc/>"
            : $"/// <inheritdoc cref=\"{name}\"/>");
    }

    /// <summary>
    ///     Add the inheritdoc comment referencing a method symbol.
    /// </summary>
    /// <param name="node">the syntax node.</param>
    /// <param name="methodSymbol">the method symbol to reference.</param>
    /// <typeparam name="TNode">the syntax node type.</typeparam>
    /// <returns>the node with inheritdoc comment trivia.</returns>
    public static TNode WithXmlComment<TNode>(this TNode node, IMethodSymbol methodSymbol)
        where TNode : SyntaxNode
    {
        return node.WithXmlComment(
            $"/// <inheritdoc cref=\"{methodSymbol.OriginalDefinition.GetName().SummaryName}\"/>");
    }

    /// <summary>
    ///     Generate a node by the string.
    /// </summary>
    /// <typeparam name="TNode">the member declaration type.</typeparam>
    /// <param name="code">the C# code to parse.</param>
    /// <returns>the parsed syntax node.</returns>
    public static TNode ParseSyntax<TNode>(string code) where TNode : MemberDeclarationSyntax
    {
        return (TNode)((CompilationUnitSyntax)ParseSyntaxTree(code).GetRoot()).Members[0];
    }

    /// <summary>
    ///     Generate the basic namespace declaration.
    /// </summary>
    /// <param name="name">the namespace name.</param>
    /// <param name="comment">the auto-generated comment.</param>
    /// <returns>the namespace declaration syntax.</returns>
    public static BaseNamespaceDeclarationSyntax NamespaceDeclaration(string name, string? comment = null)
    {
        return MakeGenerated(FileScopedNamespaceDeclaration(ParseName(name)), comment);
    }

    /// <summary>
    ///     Make the node as the auto generated.
    /// </summary>
    /// <param name="syntax">the syntax node.</param>
    /// <param name="comment">the auto-generated comment.</param>
    /// <typeparam name="T">the syntax node type.</typeparam>
    /// <returns>the node with auto-generated leading trivia.</returns>
    public static T MakeGenerated<T>(T syntax, string? comment = null) where T : SyntaxNode
    {
        var text = "// <auto-generated/>";
        if (comment != null)
            text = "// <auto-generated>"
                   + "\n" + comment.Leading("// ")
                   + "\n// </auto-generated>";

        return syntax.WithLeadingTrivia(TriviaList(
            Comment(text),
            Trivia(PragmaWarningDirectiveTrivia(Token(SyntaxKind.DisableKeyword), true)),
            Trivia(NullableDirectiveTrivia(Token(SyntaxKind.EnableKeyword), true))));
    }

    #region Attribute

    /// <summary>
    ///     Create a GeneratedCodeAttribute attribute list.
    /// </summary>
    /// <param name="generator">the generator type.</param>
    /// <returns>the attribute list syntax.</returns>
    public static AttributeListSyntax GeneratedCodeAttribute(Type generator)
    {
        return AttributeList([
            Attribute(IdentifierName("global::System.CodeDom.Compiler.GeneratedCode"))
                .AddArgumentListArguments(
                    AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression,
                        Literal(generator.FullName ?? generator.Name))),
                    AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression,
                        Literal(generator.Assembly.GetName().Version?.ToString() ?? "1.0.0"))))
        ]);
    }

    /// <summary>
    ///     Create a DebuggerNonUserCodeAttribute.
    /// </summary>
    /// <returns>the attribute syntax.</returns>
    public static AttributeSyntax NonUserCodeAttribute()
    {
        return Attribute(IdentifierName("global::System.Diagnostics.DebuggerNonUserCodeAttribute"));
    }

    /// <summary>
    ///     Create a MethodImplAttribute.
    /// </summary>
    /// <param name="methodImplOptions">the method implementation options.</param>
    /// <returns>the attribute syntax.</returns>
    [MethodImpl(MethodImplOptions.AggressiveInlining)]
    public static AttributeSyntax MethodImplAttribute(MethodImplOptions methodImplOptions)
    {
        return Attribute(IdentifierName("global::System.Runtime.CompilerServices.MethodImplAttribute"))
            .WithArgumentList(AttributeArgumentList(
            [
                AttributeArgument(MemberAccessExpression(
                    SyntaxKind.SimpleMemberAccessExpression,
                    IdentifierName("global::System.Runtime.CompilerServices.MethodImplOptions"),
                    IdentifierName("AggressiveInlining")))
            ]));
    }

    /// <summary>
    ///     Create an OverloadResolutionPriorityAttribute.
    /// </summary>
    /// <param name="priority">the overload resolution priority value.</param>
    /// <returns>the attribute syntax.</returns>
    public static AttributeSyntax OverloadResolutionPriorityAttribute(int priority)
    {
        return Attribute(IdentifierName("global::System.Runtime.CompilerServices.OverloadResolutionPriorityAttribute"))
            .WithArgumentList(AttributeArgumentList(
            [
                AttributeArgument(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(priority)))
            ]));
    }

    /// <summary>
    ///     Create an ObsoleteAttribute.
    /// </summary>
    /// <param name="message">The message to show.</param>
    /// <param name="error">make it as error.</param>
    /// <returns>the attribute syntax.</returns>
    public static AttributeSyntax ObsoleteAttribute(string message = "", bool error = false)
    {
        var attribute = Attribute(IdentifierName("global::System.Obsolete"));
        if (string.IsNullOrEmpty(message)) return attribute;
        return attribute.WithArgumentList(AttributeArgumentList(
        [
            AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(message))),
            AttributeArgument(
                LiteralExpression(error ? SyntaxKind.TrueLiteralExpression : SyntaxKind.FalseLiteralExpression))
        ]));
    }

    /// <summary>
    ///     Create a PureAttribute.
    /// </summary>
    /// <returns>the attribute syntax.</returns>
    public static AttributeSyntax PureAttribute()
    {
        return Attribute(IdentifierName("global::System.Diagnostics.Contracts.Pure"));
    }

    /// <summary>
    ///     Create a DescriptionAttribute.
    /// </summary>
    /// <param name="description">the description text.</param>
    /// <returns>the attribute syntax.</returns>
    public static AttributeSyntax DescriptionAttribute(string description)
    {
        var attributeArgument =
            AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(description)));
        return Attribute(IdentifierName("global::System.ComponentModel.Description"),
            AttributeArgumentList(SingletonSeparatedList(attributeArgument)));
    }

    #endregion

    #region Enum Member

    /// <summary>
    ///     Create an enum member with a byte value.
    /// </summary>
    /// <param name="name">the member name.</param>
    /// <param name="value">the byte value.</param>
    /// <returns>the enum member declaration syntax.</returns>
    public static EnumMemberDeclarationSyntax EnumMember(string name, byte value)
    {
        return EnumMemberDeclaration(name)
            .WithEqualsValue(EqualsValueClause(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(value))));
    }

    /// <summary>
    ///     Create an enum member with a ushort value.
    /// </summary>
    /// <param name="name">the member name.</param>
    /// <param name="value">the ushort value.</param>
    /// <returns>the enum member declaration syntax.</returns>
    public static EnumMemberDeclarationSyntax EnumMember(string name, ushort value)
    {
        return EnumMemberDeclaration(name)
            .WithEqualsValue(EqualsValueClause(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(value))));
    }

    /// <summary>
    ///     Create an enum member with a uint value.
    /// </summary>
    /// <param name="name">the member name.</param>
    /// <param name="value">the uint value.</param>
    /// <returns>the enum member declaration syntax.</returns>
    public static EnumMemberDeclarationSyntax EnumMember(string name, uint value)
    {
        return EnumMemberDeclaration(name)
            .WithEqualsValue(EqualsValueClause(LiteralExpression(SyntaxKind.NumericLiteralExpression, Literal(value))));
    }

    #endregion

    #region ITypeParameterName

    private static IEnumerable<ITypeParamName> RemoveDuplicated(this IEnumerable<ITypeParamName> names)
    {
        var nameSet = new HashSet<string>();
        return names.Where(p => nameSet.Add(p.SyntaxName));
    }

    /// <summary>
    ///     Add the parameter names for the class declaration.
    /// </summary>
    /// <param name="classDeclaration">the class declaration.</param>
    /// <param name="typeParamNames">the type parameter names.</param>
    /// <returns>the class declaration with type parameters.</returns>
    public static ClassDeclarationSyntax WithTypeParameterNames(this ClassDeclarationSyntax classDeclaration,
        params IEnumerable<ITypeParamName> typeParamNames)
    {
        var set = typeParamNames.RemoveDuplicated().ToArray();
        if (set.Length is 0) return classDeclaration;

        return classDeclaration
            .WithTypeParameterList(TypeParameterList(
            [
                .. set.Select(t => t.Syntax)
            ]))
            .WithConstraintClauses(
            [
                .. set.Select(t => t.ConstraintClause).OfType<TypeParameterConstraintClauseSyntax>()
            ]);
    }

    /// <summary>
    ///     Add the parameter names for the method declaration.
    /// </summary>
    /// <param name="methodDeclaration">the method declaration.</param>
    /// <param name="typeParamNames">the type parameter names.</param>
    /// <returns>the method declaration with type parameters.</returns>
    public static MethodDeclarationSyntax WithTypeParameterNames(this MethodDeclarationSyntax methodDeclaration,
        params IEnumerable<ITypeParamName> typeParamNames)
    {
        var set = typeParamNames.RemoveDuplicated().ToArray();
        if (set.Length is 0) return methodDeclaration;

        return methodDeclaration
            .WithTypeParameterList(TypeParameterList(
            [
                .. set.Select(t => t.Syntax)
            ]))
            .WithConstraintClauses(
            [
                .. set.Select(t => t.ConstraintClause).OfType<TypeParameterConstraintClauseSyntax>()
            ]);
    }

    /// <summary>
    ///     Add the parameter names for the interface declaration.
    /// </summary>
    /// <param name="interfaceDeclaration">the interface declaration.</param>
    /// <param name="typeParamNames">the type parameter names.</param>
    /// <returns>the interface declaration with type parameters.</returns>
    public static InterfaceDeclarationSyntax WithTypeParameterNames(
        this InterfaceDeclarationSyntax interfaceDeclaration,
        params IEnumerable<ITypeParamName> typeParamNames)
    {
        var set = typeParamNames.RemoveDuplicated().ToArray();
        if (set.Length is 0) return interfaceDeclaration;

        return interfaceDeclaration
            .WithTypeParameterList(TypeParameterList(
            [
                .. set.Select(t => t.Syntax)
            ]))
            .WithConstraintClauses(
            [
                .. set.Select(t => t.ConstraintClause).OfType<TypeParameterConstraintClauseSyntax>()
            ]);
    }

    /// <summary>
    ///     Add the parameter names for the struct declaration.
    /// </summary>
    /// <param name="structDeclaration">the struct declaration.</param>
    /// <param name="typeParamNames">the type parameter names.</param>
    /// <returns>the struct declaration with type parameters.</returns>
    public static StructDeclarationSyntax WithTypeParameterNames(
        this StructDeclarationSyntax structDeclaration,
        params IEnumerable<ITypeParamName> typeParamNames)
    {
        var set = typeParamNames.RemoveDuplicated().ToArray();
        if (set.Length is 0) return structDeclaration;

        return structDeclaration
            .WithTypeParameterList(TypeParameterList(
            [
                .. set.Select(t => t.Syntax)
            ]))
            .WithConstraintClauses(
            [
                .. set.Select(t => t.ConstraintClause).OfType<TypeParameterConstraintClauseSyntax>()
            ]);
    }

    /// <summary>
    ///     Add the parameter names for the name syntax.
    /// </summary>
    /// <param name="typeSyntax">the simple name syntax.</param>
    /// <param name="typeParamNames">the type parameter names.</param>
    /// <returns>the generic name syntax with type arguments.</returns>
    public static SimpleNameSyntax WithTypeParameterNames(this SimpleNameSyntax typeSyntax,
        params IEnumerable<ITypeParamName> typeParamNames)
    {
        string typeName;
        switch (typeSyntax)
        {
            case IdentifierNameSyntax id:
                typeName = id.Identifier.Text;
                break;

            case GenericNameSyntax generic:
                typeName = generic.Identifier.Text;
                break;

            default:
                return typeSyntax;
        }

        var set = typeParamNames.RemoveDuplicated().ToArray();
        if (set.Length is 0) return typeSyntax;

        return GenericName(typeName).WithTypeArgumentList(TypeArgumentList([
            ..set.Select(t => IdentifierName(t.SyntaxName))
        ]));
    }

    #endregion
}